// DO NOT EDIT THIS FILE.
using System.Collections.Generic;
namespace NOVNINE
{
	public static class Context
	{
		public static PlatformContext NNPlatform;
		public static UncleBillContext UncleBill;

#if USE_RemoteNotification
		public static RemoteNotification RemoteNotification;
#endif
	}
}
